name: 'Mutation Report Action'
description: 'Show mutation report annotations in GitHub'
inputs:
  repo-token:
    description: 'GitHub Token'
    required: true
  report-json:
    description: 'Mutation JSON Report Path'
    required: false
    default: './reports/mutation/mutation.json'
runs:
  using: 'node12'
  main: './src/index.js'
